### ISSUE TITLE
How to ensure maximum usage of system ressources?

### ISSUE THREAD

**Issue by ClmnsRck** [romeric/Fastor#25]
I would like to know, what compilerflags i have to set if i want to ensure, that Fastor runs at its fullest potential. Right now, i have downloaded and linked it, but not really taken further precautions.

EDIT: `-O3` and `-march=native` are being used

**Comment by romeric** [comment]
If by resources you mean performance, then you must compile with

`-O3 -march=native -DNDEBUG`

at least. Fastor can bypass a lot of checks if you issue `-DNDEBUG` to the compiler, to the point that you should never compile Fastor without this flag. Other compiler flags that you should be using

`-ffp-contract=fast`: for automatically turning SSE to AVX to FMA instructions
`-finline-functions -finline-limit=<some_high_value>`: gcc specific but Fastor loves this
`-mllvm -inline-threshold=<some_high_value>`: same as above but for clang/llvm
`-inline-forceinline -inline-factor=<some_high_value>`: same as above but for Intel ICC/ICPC 

Fastor typically chains multiple operations and then operates them all at one go and hence relies a lot on inlining. There are also Fastor specific flags for performance

`-DFASTOR_NO_ALIAS -DFASTOR_USE_VECTORISED_EXPR_ASSIGN -DCONTRACT_OPT=2`

1. `-DFASTOR_NO_ALIAS` completely ignores aliasing of pointers so proceed with caution. Overlapping assignment of tensors typically has aliasing issue, for instance:

~~~c++
Tensor<double,3,3> A;
A(seq(2,last),all).noalias() += A(seq(0,last-2),all);
~~~

In this case, tensor `A` appears on both sides and a portion of it has to be added to itself. You need the `noalias` macro to tell Fastor to make a copy internally before adding a part of `A` to another part of `A`. Note that for perfect overlapping you don't need the `noalias` operator call, for instance in:

~~~c++
A(seq(0,last-2),all).noalias() += A(seq(0,last-2),all);
~~~
or 
~~~c++
A(seq(2,last),all).noalias() += A(seq(2,last),all);
~~~

because the same portion of `A` is added to `A`, so one can go sequentially and keep adding the elements of the tensor.

2. `-DFASTOR_USE_VECTORISED_EXPR_ASSIGN` is really beneficial on recent Intel cpus as Fastor can evaluate multiple expressions using SIMD at one go.

3. `-DCONTRACT_OPT=2` pertains to Fastor's compile time evaluation when you are using Einstein summation, permutations etc.  `-DCONTRACT_OPT=0` is the lowest level and  `-DCONTRACT_OPT=2` is the highest level. The structure of the resulting tensor is completely evaluated at compile time if  `-DCONTRACT_OPT=2` is performed. Note that this also might blow up your compile time, so better stick to  `-DCONTRACT_OPT=1`.

Hope that answers your question.

**Comment by ClmnsRck** [comment]
I'll definitely work with it now, thanks.
