### ISSUE TITLE
Possibility to use column major layout

### ISSUE THREAD

**Issue by matthiasneuner** [romeric/Fastor#32]
Is it possible to interface with raw data organized in column major layout?

**Comment by romeric** [comment]
If by interface you mean wrapping over the column major data then NO. This is one area that would require considerable refactoring if an optimised code is needed. If you use TensorRef feature then you can interface with Fastor only in non-vectorised mode. 

If you are willing to make a copy while going in and out of Fastor Tensors, then yeah very possible. Fastor is for stack-allocated data only and making copies generally does not hurt performance as the data is already in cache. I have had developers interface with Fastor this way before.

I will soon add a constructor to the Fastor::Tensor to allow specfying data format.

Thanks

**Comment by macmallow** [comment]
Alright, thank you!

PS: Looking forward to a documentation; I really like your project but I believe such a project is crucially dependent on a proper documentation in order to attract other developers.

**Comment by matthiasneuner** [comment]
Is there any update on the Fastor::Tensor constructor to specifiy the data layout of an existing array, i.e., a possiblity to easily interface with Eigen matrices/tensors?

**Comment by romeric** [comment]
Yes, I am currently working on this. The feature will be available in a few days hopefully. Think to note though is that changing the tensor layout also reverses the dimensions so I am trying to make this as less confusing as possible

**Comment by romeric** [comment]
This feature has now been implemented. To interface with column-major matrices/tensors you have a few options now

1 . You can construct a Fastor `Tensor` by specifying the layout to the constructor, for instance with Eigen matrices say

~~~c++
Eigen::Matrix<double,3,4> ea;
std::iota(ea.data(),ea.data()+12,1.);
std::cout << ea << std::endl;
~~~
~~~
 1  4  7 10
 2  5  8 11
 3  6  9 12
~~~

Which is of course column-major. Now, to construct a Fastor `Tensor` you do

~~~
Tensor<double,3,4> fa(ea.data(),Fastor::ColumnMajor);
~~~

You can perform computation on `fa` now 

~~~c++
fa += 2;
std::cout << fa << std::endl;
~~~
~~~
[ 3,  6,  9, 12]
[ 4,  7, 10, 13]
[ 5,  8, 11, 14]
~~~

To change back to Eigen matrix, it is *necessary* to convert back to row-major first and then use `Eigen::Map`

~~~c++
Tensor<double,3,4> fb = torowmajor(fa);
Eigen::Map<Eigen::Matrix<double,3,4>> eb(fb.data());
std::cout << eb << std::endl;
~~~
~~~
 3  6  9 12
 4  7 10 13
 5  8 11 14
~~~

Otherwise Eigen will assume contiguity is in other axis and will swap the data for you. Note that all of these matrices are copies as Fastor internally treats everything as row-major, so changing `fa` will not change `ea` until you convert them back to Eigen matrices. This copy is really cheap though.

2. There is also a free function `tocolumnmajor` that you can after constructing a `Fastor::Tensor`

~~~
Tensor<double,3,4> fa(ea.data());
Tensor<double,3,4> fb = tocolumnmajor(fa);
~~~

3. Of course you can `Eigen::Tensor` and `Eigen::TensorMap` in the same fashion

4. If your data is already in row-major format, you can directly map them to Fastor format using `Fastor::TensorMap`

~~~c++
Eigen::TensorFixedSize<double,Eigen::Sizes<2,3,4>, Eigen::RowMajor> ea;
std::iota(ea.data(),ea.data()+24,1.);
std::cout << "Eigen row-major tensor (ea)\n" << ea << std::endl;
TensorMap<double,2,3,4> fa(ea.data());
fa += 2;
std::cout << "Eigen row-major tensor modified by Fastor (ea+2) \n" << ea << std::endl;
~~~
~~~
Eigen row-major tensor (ea)
 1  2  3  4  5  6  7  8  9 10 11 12
13 14 15 16 17 18 19 20 21 22 23 24

Eigen row-major tensor modified by Fastor (ea+2)
 3  4  5  6  7  8  9 10 11 12 13 14
15 16 17 18 19 20 21 22 23 24 25 26
~~~

Note that `Fastor::TensorMap` just wraps around existing data and does not make any copies so changing the `fa` in this case changes `ea`. You can use `Fastor::TensorMap` exactly like `Fastor::Tensor`. It has almost all of the functionality of a `Fastor::Tensor`. 

Hope this meets your requirement(s).

**Comment by matthiasneuner** [comment]
Thank you, that perfectly meets my requirements!
