### ISSUE TITLE
Slower than Eigen for big matrices

### ISSUE THREAD

**Issue by nicolov** [romeric/Fastor#42]
Thanks a lot for the release, the code looks great. I've adapted [my benchmark code](https://github.com/nicolov/robotics_benchmarks/pull/3) to try your library. The code just does a bunch of inverse and mmuls to simulate a Kalman filter.

Fastor is ~2x faster than Eigen for small matrices (which is amazing), is as fast as Eigen for 64-size matrices, but roughly ~2x slower for 128-size matrices. This is `-mavx` on an i9-9700k with gcc 8. Do you have any idea why this might be the case?

```
Run on (8 X 4900 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x8)
  L1 Instruction 32 KiB (x8)
  L2 Unified 256 KiB (x8)
  L3 Unified 12288 KiB (x1)
Load Average: 1.08, 0.79, 0.41
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
CovarianceUpdateFastor<8>                        241 ns          241 ns      2836716
CovarianceUpdateEigen<8>/8                       393 ns          393 ns      1771414
CovarianceUpdateEigen<Eigen::Dynamic>/8          822 ns          822 ns       830852
CovarianceUpdateFastor<16>                      1144 ns         1144 ns       610699
CovarianceUpdateEigen<16>/16                    2117 ns         2117 ns       333241
CovarianceUpdateEigen<Eigen::Dynamic>/16        2352 ns         2352 ns       298774
CovarianceUpdateFastor<32>                      7689 ns         7689 ns        90656
CovarianceUpdateEigen<32>/32                    9936 ns         9936 ns        69588
CovarianceUpdateEigen<Eigen::Dynamic>/32        8752 ns         8752 ns        78695
CovarianceUpdateFastor<64>                     44389 ns        44389 ns        15646
CovarianceUpdateEigen<64>/64                   49503 ns        49503 ns        13345
CovarianceUpdateEigen<Eigen::Dynamic>/64       48440 ns        48440 ns        14342
CovarianceUpdateFastor<128>                   449163 ns       449160 ns         1584
CovarianceUpdateEigen<128>/128                339488 ns       339446 ns         2104
CovarianceUpdateEigen<Eigen::Dynamic>/128     330540 ns       330537 ns         2167
```

**Comment by mratsim** [comment]
That's because Fastor is using triple for-loop to implement matrix multiplication.

In comparison, BLAS libraries like Eigen (which is probably the slowest among BLAS libraries like OpenBLAS, MKL and BLIS) are using L1 and L2 cache tiling, register tiling, multiple threads and repacking/swizzling the input matrices into a format more suitable for vectorization. This is a significant (and unnecessary overhead) on small matrices but necessary to use 100% of the CPU compute instead of being limited by memory bandwidth on larger matrices which happens when using triple for-loop.

**Comment by romeric** [comment]
The culprit here is that Fastor does not have a special routine for `matmual(A,transpose(B))`. All other BLAS libraries do (in BLAS terminology think `dgemm(CblasTrans, CblasNoTrans)`). Fastor instead creates a temporary tensor for `transpose` while Eigen does not. So when the tensor size is big enough for the L2 cache and spills over to L3 cache the perforamnce drops down.  Not creating a temporary is possible with Fastor but at the moment requires a bit of tuning. 

@mratsim is correct. While Fastor does have an efficient SIMD vectorised `matmul` algorithm, it is designed for on-the-cache matrices primarily. It does not do anything special with the memory. For bigger matrices you are going to get a much better performance using vendor BLAS.

On a side note can you try the latest commit of 0b49523 of Fastor. You might get a slightly better performance with GCC.

**Comment by nicolov** [comment]
Interesting, thanks to both for the insight. Since we're talking about `matmul`, is there an infix operator I can use? The infix function becomes pretty unwieldy.

> we are not exactly 2X slower than Eigen

Yes, sorry. I mis-remembered a previous number I'd eyeballed.

**Comment by romeric** [comment]
Apologies for the delayed response. 

No there is no infix operator for matrix mulitplication at the moment. Our rational was that Fastor is essentially a tensor (multi-dimensional array) library and not a matrix library like Eigen and others, so if `*` meant matrix-matrix multiplication for second order tensors (i.e. matrices) what would it mean for higher order tensors?. There are many ways you could multiply/contract two high order tensors (along any arbitrary dimension(s)), which is why we designed the `einsum`, `contraction`, `permutation` etc, but put `matmul` to specfically indicate matrix-matrix multiplication between second order tensors. 

Overloading an operator that would work strictly on 2D tensors and not on higher order tensors sounded like a bit a flawed design for us at the time. You are welcome to suggest though, if you have an idea.

**Comment by nicolov** [comment]
That makes sense, thanks.

> You are welcome to suggest though, if you have an idea.

None other than overloading some other operator, like numpy's `@`. I guess in C++, that only leaves `^`, but I don't want to go on the record suggesting that :D

**Comment by romeric** [comment]
With some of the latest commits, I have now provided a BLAS (specifically [libxsmm](https://github.com/hfp/libxsmm)) backend to matmul subroutines. You can now run Fastor with it's in-built matmul or switch to a vendor BLAS implementation if you want to without changing your code (as is the case with BLAS implementations). The switch can also be configured based on square and non-square matrix sizes using compiler flags `BLAS_SWITCH_MATRIX_SIZE_S` and `BLAS_SWITCH_MATRIX_SIZE_NS`. The default value is 17 for square matrices, that is matrices with sizes equal or bigger than `17x17` will be dispatched to BLAS if one is available. But might be best experimenting with this value on your own architecture. At the moment to enable `libxsmm` backend you can use the `-DUSE_LIBXSMM_BACKEND` flag while compiling.

Running your benchmark on my Macbook-Pro 2018 with `-mavx2 -mfma` and Fastor's in-built backend I get 

```
Run on (8 X 2300 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x4)
  L1 Instruction 32 KiB (x4)
  L2 Unified 256 KiB (x4)
  L3 Unified 6144 KiB (x1)
Load Average: 1.31, 1.23, 1.06
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
CovarianceUpdateFastor<8>                        261 ns          261 ns      2574429
CovarianceUpdateEigen<8>/8                       361 ns          360 ns      1941064
CovarianceUpdateEigen<Eigen::Dynamic>/8         1584 ns         1584 ns       443867
CovarianceUpdateFastor<16>                      1117 ns         1116 ns       614202
CovarianceUpdateEigen<16>/16                    2358 ns         2357 ns       295755
CovarianceUpdateEigen<Eigen::Dynamic>/16        3061 ns         3058 ns       227046
CovarianceUpdateFastor<32>                      7025 ns         7019 ns        99416
CovarianceUpdateEigen<32>/32                    9583 ns         9579 ns        71663
CovarianceUpdateEigen<Eigen::Dynamic>/32        8467 ns         8462 ns        80805
CovarianceUpdateFastor<64>                     48338 ns        48306 ns        14543
CovarianceUpdateEigen<64>/64                   39455 ns        39440 ns        17969
CovarianceUpdateEigen<Eigen::Dynamic>/64       43240 ns        43211 ns        16201
CovarianceUpdateFastor<128>                   361356 ns       361054 ns         1912
CovarianceUpdateEigen<128>/128                252530 ns       252427 ns         2750
CovarianceUpdateEigen<Eigen::Dynamic>/128     253395 ns       253237 ns         2769
```

and with libxsmm backend (libxsmm compiled as `make -STATIC=0 AVX=2` and linked as `-L/path/to/libxsmm/lib/ -lxsmm -lblas -ldl`), I get

```
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
CovarianceUpdateFastor<8>                        264 ns          264 ns      2614574
CovarianceUpdateEigen<8>/8                       361 ns          361 ns      1916690
CovarianceUpdateEigen<Eigen::Dynamic>/8         1551 ns         1550 ns       438844
CovarianceUpdateFastor<16>                      1127 ns         1127 ns       620507
CovarianceUpdateEigen<16>/16                    2382 ns         2381 ns       295006
CovarianceUpdateEigen<Eigen::Dynamic>/16        3024 ns         3023 ns       226108
CovarianceUpdateFastor<32>                      5553 ns         5550 ns       123622
CovarianceUpdateEigen<32>/32                    9573 ns         9563 ns        73413
CovarianceUpdateEigen<Eigen::Dynamic>/32        8302 ns         8297 ns        83336
CovarianceUpdateFastor<64>                     30319 ns        30296 ns        23204
CovarianceUpdateEigen<64>/64                   40625 ns        40593 ns        17266
CovarianceUpdateEigen<Eigen::Dynamic>/64       42952 ns        42913 ns        16350
CovarianceUpdateFastor<128>                   204550 ns       195397 ns         3583
CovarianceUpdateEigen<128>/128                253779 ns       253609 ns         2777
CovarianceUpdateEigen<Eigen::Dynamic>/128     254236 ns       254065 ns         2779
```

That is not the end of the story though. Your benchmark can be optimised much more in Fastor if you use specialised tensors, instead of just `Tensor`. For you example you can use `SingleValueTensor` instead of `Tensor` for a couple of your matrices. `SingleValueTensor` is a special tensor of any dimension and size whose elements are equal (for intance a matrix of ones). At the moment, this is an experimental feature (fairly stable though and will be part of the library in one of the upcoming releases), as I am going to work on a few more specialised tensors such as `IdentityTensor`, `SymmetricTensor` and so on, that Fastor lacks at the moment. These specialised tensors can provide optimised matrix multiplication, inversion and so on.

So by `#include <experimental/SingleValueTensor.h>`

and changing these lines 

~~~c++
  Tensor<NumType, CStateSize, CStateSize> P_x; P_x.ones();
  P_x = matmul(transpose(P_x), P_x);
~~~  
to 
~~~c++
  SingleValueTensor<NumType, CStateSize, CStateSize> P_x0(1);
  SingleValueTensor<NumType, CStateSize, CStateSize> P_x = matmul(transpose(P_x0), P_x0);
~~~  
and this line
~~~c++
  Tensor<NumType, CObsSize, CStateSize> H_dx(1);
  H_dx.ones();
~~~  
to 
~~~c++
SingleValueTensor<NumType, CObsSize, CStateSize> H_dx(1);
~~~
I get

with SingleValueTensor + in-build backend
```
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
CovarianceUpdateFastor<8>                       95.2 ns         95.1 ns      7528744
CovarianceUpdateEigen<8>/8                       372 ns          372 ns      1877934
CovarianceUpdateEigen<Eigen::Dynamic>/8         1587 ns         1587 ns       426078
CovarianceUpdateFastor<16>                       496 ns          496 ns      1411606
CovarianceUpdateEigen<16>/16                    2390 ns         2389 ns       290277
CovarianceUpdateEigen<Eigen::Dynamic>/16        3107 ns         3105 ns       226120
CovarianceUpdateFastor<32>                      3241 ns         3237 ns       218377
CovarianceUpdateEigen<32>/32                    9692 ns         9688 ns        71000
CovarianceUpdateEigen<Eigen::Dynamic>/32        8647 ns         8643 ns        79220
CovarianceUpdateFastor<64>                     23400 ns        23391 ns        29948
CovarianceUpdateEigen<64>/64                   40031 ns        39998 ns        17575
CovarianceUpdateEigen<Eigen::Dynamic>/64       43312 ns        43282 ns        16242
CovarianceUpdateFastor<128>                   178816 ns       178724 ns         3898
CovarianceUpdateEigen<128>/128                253626 ns       253508 ns         2776
CovarianceUpdateEigen<Eigen::Dynamic>/128     250998 ns       250870 ns         2768
```

and finally with SingleValueTensor + libxsmm backend
```
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
CovarianceUpdateFastor<8>                       93.5 ns         93.5 ns      7216867
CovarianceUpdateEigen<8>/8                       360 ns          360 ns      1938156
CovarianceUpdateEigen<Eigen::Dynamic>/8         1614 ns         1613 ns       428197
CovarianceUpdateFastor<16>                       486 ns          486 ns      1424026
CovarianceUpdateEigen<16>/16                    2377 ns         2376 ns       293181
CovarianceUpdateEigen<Eigen::Dynamic>/16        3052 ns         3048 ns       230069
CovarianceUpdateFastor<32>                      2580 ns         2577 ns       271706
CovarianceUpdateEigen<32>/32                    9617 ns         9613 ns        71919
CovarianceUpdateEigen<Eigen::Dynamic>/32        8345 ns         8342 ns        83752
CovarianceUpdateFastor<64>                     17013 ns        16981 ns        41993
CovarianceUpdateEigen<64>/64                   40646 ns        40609 ns        17235
CovarianceUpdateEigen<Eigen::Dynamic>/64       42646 ns        42622 ns        16399
CovarianceUpdateFastor<128>                   116042 ns       110905 ns         6268
CovarianceUpdateEigen<128>/128                253493 ns       253414 ns         2758
CovarianceUpdateEigen<Eigen::Dynamic>/128     254382 ns       254233 ns         2698
```

Cheers

**Comment by nicolov** [comment]
Wow, thanks for all this information and for the outstanding work.
